global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'maester-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:8000']
        labels:
          service: 'maester-backend'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
        labels:
          service: 'maester-redis'
